spring:
  batch:
    job:
      enabled: false
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:maindb
  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${MONGODB_DATABASE:book_library}
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:mongodb_secret}
      authentication-database: admin
      auto-index-creation: true
      event-listeners:
        enabled: true
  liquibase:
    enabled: true
    contexts: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true