services:
  app:
    env_file: ./env/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    env_file:
      - ./env/.env
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - hw17_data:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - ./env/.env
    ports:
      - "5050:80"
    image: dpage/pgadmin4:latest

volumes:
  hw17_data: