services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/HW17
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - hw17_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=HW17
    command: >
      postgres
      -c log_statement=all
      -c log_min_duration_statement=0
      -c log_parameter_max_length=0
      -c log_line_prefix='%t [%p]: '
      -c log_destination=stderr
      -c log_error_verbosity=verbose

  pgadmin:
    ports:
      - "5050:80"
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False


volumes:
  hw17_data: