spring:
  messages:
    encoding: UTF-8

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:mem:maindb

  shell:
    interactive:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    contexts: dev

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true