version: '3.8'

services:
  mongo:
    image: mongo:8.0.12
    env_file:
      - .env
    container_name: hw08-mongo-1
    command: mongod --bind_ip_all
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - mongo11_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - mongo-network

  mongoexpress:
    image: mongo-express:1.0.2
    env_file:
      - .env
    container_name: hw08-mongoexpress-1
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/${MONGODB_DATABASE}?authSource=admin
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/status || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
volumes:
  mongo11_data: