spring:

  output:
    ansi:
      enabled: ALWAYS

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${MONGODB_DATABASE:book_library}
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:mongodb_secret}
      authentication-database: admin
      auto-index-creation: true
      event-listeners:
        enabled: true

  shell:
    interactive:
      enabled: true

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local



