name: Build

on:
  pull_request:

jobs:
  build-java-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-java-app
        # Можно переопределить параметры по умолчанию:
        # with:
        #   java-version: '17'
        #   distribution: 'temurin'
        #   maven-args: 'verify --no-transfer-progress'

  notify-telegram:
    runs-on: ubuntu-latest
    needs: build-java-app
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/notify-telegram-pr
        with:
          bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          build-result: ${{ needs.build-java-app.result }}